GoturWebApp/Controllers/CategoryController.cs
using GoturWebApp.Data;
using GoturWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace GoturWebApp.Controllers
{
    public class CategoryController : Controller
    {
        private readonly GoturDbContext db;

        public CategoryController(GoturDbContext _db)
        {
            this.db = _db;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> objCategoryList = db.Categories.ToList();
            return View(objCategoryList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            //Burda password validation yapabilirsin, name yerine password de
            if(obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "The DisplayOrder cannot exactly match the Name.");
            }
            if (ModelState.IsValid)
            {
                db.Categories.Add(obj);
                db.SaveChanges();
                TempData["success"] = "Category created successfully!";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            if(id==null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = db.Categories.Find(id);
            //var categoryFromDbFirst = db.Categories.FirstOrDefault(u => u.Id == id);
            //var categoryFromDbSingle = db.Categories.SingleOrDefault(u => u.Id == id);
            
            if(categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            //Burda password validation yapabilirsin, name yerine password de
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "The DisplayOrder cannot exactly match the Name.");
            }
            if (ModelState.IsValid)
            {
                db.Categories.Update(obj);
                db.SaveChanges();
                TempData["success"] = "Category updated successfully!";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = db.Categories.Find(id);
            //var categoryFromDbFirst = db.Categories.FirstOrDefault(u => u.Id == id);
            //var categoryFromDbSingle = db.Categories.SingleOrDefault(u => u.Id == id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = db.Categories.Find(id);

            if (obj == null)
            {
                return NotFound();
            }
            
            db.Categories.Remove(obj);
            db.SaveChanges();
            TempData["success"] = "Category removed successfully!";
            return RedirectToAction("Index");
        }

    }
}

GoturWebApp/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using GoturWebApp.Models;
using GoturWebApp.Data;
using GoturWebApp.Controllers;

namespace GoturWebApp.Controllers
{
    public class LoginController : Controller
    {
        private readonly GoturDbContext db;

        public LoginController(GoturDbContext _db)
        {
            this.db = _db;
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(Customer obj)
        {
            if (obj.Customer_Name != null && obj.CustomerPassword != null && obj.Address != null)
            {
                db.Customers.Add(obj);
                db.SaveChanges();
                TempData["success"] = "Account created successfully!";
                HomeController.loginedID = obj.CustomerID;
                Basket newBasket = new Basket(obj.CustomerID);
                db.Basket.Add(newBasket);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            TempData["error"] = "Error while creating an account.";
            return View(obj);
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(Customer obj)
        {
            var customerLogined = db.Customers.FirstOrDefault(x => x.Customer_Name == obj.Customer_Name && x.CustomerPassword == obj.CustomerPassword);
            if (customerLogined!=null)
            {
                TempData["success"] = "Logined successfully!";
                HomeController.loginedID = customerLogined.CustomerID;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["error"] = "Wrong username or password. Try again.";
                return View(obj);
            }
            
        }

        public IActionResult Logout()
        {
            HomeController.loginedID = -1;
            return RedirectToAction("Index", "Home");
        }
    }
}

GoturWebApp/Controllers/OrderController.cs
using GoturWebApp.Data;
using GoturWebApp.Models;
using GoturWebApp.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace GoturWebApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly GoturDbContext db;

        public OrderController(GoturDbContext _db)
        {
            this.db = _db;
        }

        public IActionResult Orders()
        {
            var customer = db.Customers.Find(HomeController.loginedID);
            var orderList = (from o in db.Orders
                              join c in db.Customers
                              on o.CustomerID equals c.CustomerID
                              select new ViewModelOrder
                              {
                                  OrderID = o.OrderID,
                                  OrderDate = o.DateOrdered,
                                  CustomerID = c.CustomerID,
                              });
            return View(orderList.Where(l => l.CustomerID == HomeController.loginedID));
        }

        public IActionResult OrderDetails(int id)
        {
            var order = db.Orders.Find(id);
            var orderDetails = (from od in db.OrderDetails
                             join o in db.Orders
                             on od.OrderID equals o.OrderID
                             join p in db.Products on od.ProductID equals p.ProductID
                             select new ViewModelOrderDetails
                             {
                                 OrderID = o.OrderID,
                                 OrderDetailsID = od.OrderDetailsID,
                                 ProductID = p.ProductID,
                                 ProductName = p.Name,
                                 ProductPrice = p.Price,
                                 ProductPhoto = p.PhotoLink
                             });
            return View(orderDetails.Where(l=> l.OrderID == id));
        }

        public IActionResult Delete(int id)
        {
            Order? orderRef = db.Orders.FirstOrDefault(o => o.CustomerID == HomeController.loginedID);

            if (orderRef == null)
            {
                TempData["error"] = "Order could not be found.";
                return RedirectToAction("Orders");
            }
            db.Orders.Remove(orderRef);
            db.SaveChanges();
            TempData["success"] = "Order removed successfully!";
            return RedirectToAction("Orders");
        }

        public IActionResult Order(int id)
        {
            var basket = db.Basket.Find(id);
            return View(basket);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Order(Basket obj)
        {
            if (HomeController.loginedID == -1)
            {
                TempData["error"] = "You have to login first.";
                return RedirectToAction("Login", "Login");
            }

            Order newOrder = new Order(HomeController.loginedID, "ordered");
            db.Orders.Add(newOrder);
            db.SaveChanges();

            var basketList = (from b in db.Basket 
                              join c in db.Customers on b.CustomerID equals c.CustomerID
                              join o in db.Orders on c.CustomerID equals o.CustomerID
                              join bd in db.BasketDetail on b.BasketID equals bd.BasketID
                              join p in db.Products on bd.ProductID equals p.ProductID
                              select new{
                                  OrderID = o.OrderID,
                                  CustomerID = c.CustomerID,
                                  ProductID = p.ProductID,
                              });

            foreach (var l in basketList.Where(l => l.OrderID == newOrder.OrderID))
            {
                OrderDetail newDetail = new OrderDetail(newOrder.OrderID, l.ProductID);
                db.OrderDetails.Add(newDetail);
            }
            db.BasketDetail.RemoveRange(db.BasketDetail);
            db.SaveChanges();

            TempData["success"] = "Ordered successfully.";
            return RedirectToAction("Index", "Home");
        }
    }
}

GoturWebApp/Views/Shared/_Layout.cshtml
@using GoturWebApp.Controllers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GoturApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GoturWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Götür</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                    @if(HomeController.loginedID == -1)
                    {
                        <li class="nav-item"><a class="nav-link active" aria-current="page" asp-controller="Login" asp-action="Register">Register</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" asp-controller="Login" asp-action="Login">Login</a></li>
                    }
                    else{
                        <li class="nav-item"><a class="nav-link active" aria-current="page" asp-controller="Order" asp-action="Orders">My Orders</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" asp-controller="Login" asp-action="Logout">Logout</a></li>
                        
                    }
                    
                    </ul>
                    <div class="nav-item nav-link active text-black">Welcome @ViewBag.Name</div>
                    <form class="d-flex" method="post" asp-controller="Basket" asp-action="Basket">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill"></span>
                        </button>
                    </form>
                </div>
            </div>
        </nav>
    @*<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GoturWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>*@
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>
    <!-- Footer-->
        <footer id="footer" class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Götür 2022</p></div>
        </footer>
    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GoturWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GoturWebApp/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
        </script>
}

@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
        </script>
}